[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
license = "MIT"
name = "better-users"
version = "0.1.0"

[dependencies]
chrono = "0.4.3"
csv = "1.0.0"
regex = "1.0.0"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
sha2 = "0.7.1"
