[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "better-users"
version = "0.1.0"
license = "MIT"

[dependencies]
csv = "1.0.0"
regex = "1.0.0"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
sha2 = "0.7.1"
